/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Descriptor from './Descriptor';
import Id from './Id';

/**
 * The CancelPostRequestMessage model module.
 * @module model/CancelPostRequestMessage
 * @version 1.1.0
 */
class CancelPostRequestMessage {
    /**
     * Constructs a new <code>CancelPostRequestMessage</code>.
     * @alias module:model/CancelPostRequestMessage
     * @param orderId {module:model/Id} 
     */
    constructor(orderId) { 
        
        CancelPostRequestMessage.initialize(this, orderId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderId) { 
        obj['order_id'] = orderId;
    }

    /**
     * Constructs a <code>CancelPostRequestMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CancelPostRequestMessage} obj Optional instance to populate.
     * @return {module:model/CancelPostRequestMessage} The populated <code>CancelPostRequestMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CancelPostRequestMessage();

            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = Id.constructFromObject(data['order_id']);
            }
            if (data.hasOwnProperty('cancellation_reason_id')) {
                obj['cancellation_reason_id'] = Id.constructFromObject(data['cancellation_reason_id']);
            }
            if (data.hasOwnProperty('descriptor')) {
                obj['descriptor'] = Descriptor.constructFromObject(data['descriptor']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CancelPostRequestMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CancelPostRequestMessage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CancelPostRequestMessage.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `descriptor`
        if (data['descriptor']) { // data not null
          Descriptor.validateJSON(data['descriptor']);
        }

        return true;
    }


}

CancelPostRequestMessage.RequiredProperties = ["order_id"];

/**
 * @member {module:model/Id} order_id
 */
CancelPostRequestMessage.prototype['order_id'] = undefined;

/**
 * @member {module:model/Id} cancellation_reason_id
 */
CancelPostRequestMessage.prototype['cancellation_reason_id'] = undefined;

/**
 * @member {module:model/Descriptor} descriptor
 */
CancelPostRequestMessage.prototype['descriptor'] = undefined;






export default CancelPostRequestMessage;

