/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CancelPostRequestContext from './CancelPostRequestContext';
import CancelPostRequestMessage from './CancelPostRequestMessage';

/**
 * The CancelPostRequest model module.
 * @module model/CancelPostRequest
 * @version 1.1.0
 */
class CancelPostRequest {
    /**
     * Constructs a new <code>CancelPostRequest</code>.
     * @alias module:model/CancelPostRequest
     * @param context {module:model/CancelPostRequestContext} 
     * @param message {module:model/CancelPostRequestMessage} 
     */
    constructor(context, message) { 
        
        CancelPostRequest.initialize(this, context, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, context, message) { 
        obj['context'] = context;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>CancelPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CancelPostRequest} obj Optional instance to populate.
     * @return {module:model/CancelPostRequest} The populated <code>CancelPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CancelPostRequest();

            if (data.hasOwnProperty('context')) {
                obj['context'] = CancelPostRequestContext.constructFromObject(data['context']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = CancelPostRequestMessage.constructFromObject(data['message']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CancelPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CancelPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CancelPostRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `context`
        if (data['context']) { // data not null
          CancelPostRequestContext.validateJSON(data['context']);
        }
        // validate the optional field `message`
        if (data['message']) { // data not null
          CancelPostRequestMessage.validateJSON(data['message']);
        }

        return true;
    }


}

CancelPostRequest.RequiredProperties = ["context", "message"];

/**
 * @member {module:model/CancelPostRequestContext} context
 */
CancelPostRequest.prototype['context'] = undefined;

/**
 * @member {module:model/CancelPostRequestMessage} message
 */
CancelPostRequest.prototype['message'] = undefined;






export default CancelPostRequest;

