/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DescriptorAdditionalDesc model module.
 * @module model/DescriptorAdditionalDesc
 * @version 1.1.0
 */
class DescriptorAdditionalDesc {
    /**
     * Constructs a new <code>DescriptorAdditionalDesc</code>.
     * @alias module:model/DescriptorAdditionalDesc
     */
    constructor() { 
        
        DescriptorAdditionalDesc.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DescriptorAdditionalDesc</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DescriptorAdditionalDesc} obj Optional instance to populate.
     * @return {module:model/DescriptorAdditionalDesc} The populated <code>DescriptorAdditionalDesc</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DescriptorAdditionalDesc();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DescriptorAdditionalDesc</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DescriptorAdditionalDesc</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['content_type'] && !(typeof data['content_type'] === 'string' || data['content_type'] instanceof String)) {
            throw new Error("Expected the field `content_type` to be a primitive type in the JSON string but got " + data['content_type']);
        }

        return true;
    }


}



/**
 * @member {String} url
 */
DescriptorAdditionalDesc.prototype['url'] = undefined;

/**
 * @member {module:model/DescriptorAdditionalDesc.ContentTypeEnum} content_type
 */
DescriptorAdditionalDesc.prototype['content_type'] = undefined;





/**
 * Allowed values for the <code>content_type</code> property.
 * @enum {String}
 * @readonly
 */
DescriptorAdditionalDesc['ContentTypeEnum'] = {

    /**
     * value: "text/plain"
     * @const
     */
    "text/plain": "text/plain",

    /**
     * value: "text/html"
     * @const
     */
    "text/html": "text/html",

    /**
     * value: "application/json"
     * @const
     */
    "application/json": "application/json"
};



export default DescriptorAdditionalDesc;

