/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Image model module.
 * @module model/Image
 * @version 1.1.0
 */
class Image {
    /**
     * Constructs a new <code>Image</code>.
     * Describes an image
     * @alias module:model/Image
     */
    constructor() { 
        
        Image.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Image</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Image} obj Optional instance to populate.
     * @return {module:model/Image} The populated <code>Image</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Image();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('size_type')) {
                obj['size_type'] = ApiClient.convertToType(data['size_type'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'String');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Image</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Image</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['size_type'] && !(typeof data['size_type'] === 'string' || data['size_type'] instanceof String)) {
            throw new Error("Expected the field `size_type` to be a primitive type in the JSON string but got " + data['size_type']);
        }
        // ensure the json data is a string
        if (data['width'] && !(typeof data['width'] === 'string' || data['width'] instanceof String)) {
            throw new Error("Expected the field `width` to be a primitive type in the JSON string but got " + data['width']);
        }
        // ensure the json data is a string
        if (data['height'] && !(typeof data['height'] === 'string' || data['height'] instanceof String)) {
            throw new Error("Expected the field `height` to be a primitive type in the JSON string but got " + data['height']);
        }

        return true;
    }


}



/**
 * URL to the image. This can be a data url or an remote url
 * @member {String} url
 */
Image.prototype['url'] = undefined;

/**
 * The size of the image. The network policy can define the default dimensions of each type
 * @member {module:model/Image.SizeTypeEnum} size_type
 */
Image.prototype['size_type'] = undefined;

/**
 * Width of the image in pixels
 * @member {String} width
 */
Image.prototype['width'] = undefined;

/**
 * Height of the image in pixels
 * @member {String} height
 */
Image.prototype['height'] = undefined;





/**
 * Allowed values for the <code>size_type</code> property.
 * @enum {String}
 * @readonly
 */
Image['SizeTypeEnum'] = {

    /**
     * value: "xs"
     * @const
     */
    "xs": "xs",

    /**
     * value: "sm"
     * @const
     */
    "sm": "sm",

    /**
     * value: "md"
     * @const
     */
    "md": "md",

    /**
     * value: "lg"
     * @const
     */
    "lg": "lg",

    /**
     * value: "xl"
     * @const
     */
    "xl": "xl",

    /**
     * value: "custom"
     * @const
     */
    "custom": "custom"
};



export default Image;

