/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InitPostRequestContext from './InitPostRequestContext';
import SelectPostRequestMessage from './SelectPostRequestMessage';

/**
 * The InitPostRequest model module.
 * @module model/InitPostRequest
 * @version 1.1.0
 */
class InitPostRequest {
    /**
     * Constructs a new <code>InitPostRequest</code>.
     * @alias module:model/InitPostRequest
     * @param context {module:model/InitPostRequestContext} 
     * @param message {module:model/SelectPostRequestMessage} 
     */
    constructor(context, message) { 
        
        InitPostRequest.initialize(this, context, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, context, message) { 
        obj['context'] = context;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>InitPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InitPostRequest} obj Optional instance to populate.
     * @return {module:model/InitPostRequest} The populated <code>InitPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InitPostRequest();

            if (data.hasOwnProperty('context')) {
                obj['context'] = InitPostRequestContext.constructFromObject(data['context']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = SelectPostRequestMessage.constructFromObject(data['message']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InitPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InitPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InitPostRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `context`
        if (data['context']) { // data not null
          InitPostRequestContext.validateJSON(data['context']);
        }
        // validate the optional field `message`
        if (data['message']) { // data not null
          SelectPostRequestMessage.validateJSON(data['message']);
        }

        return true;
    }


}

InitPostRequest.RequiredProperties = ["context", "message"];

/**
 * @member {module:model/InitPostRequestContext} context
 */
InitPostRequest.prototype['context'] = undefined;

/**
 * @member {module:model/SelectPostRequestMessage} message
 */
InitPostRequest.prototype['message'] = undefined;






export default InitPostRequest;

