/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Rating from './Rating';

/**
 * The RatingPostRequestMessage model module.
 * @module model/RatingPostRequestMessage
 * @version 1.1.0
 */
class RatingPostRequestMessage {
    /**
     * Constructs a new <code>RatingPostRequestMessage</code>.
     * @alias module:model/RatingPostRequestMessage
     */
    constructor() { 
        
        RatingPostRequestMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RatingPostRequestMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RatingPostRequestMessage} obj Optional instance to populate.
     * @return {module:model/RatingPostRequestMessage} The populated <code>RatingPostRequestMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RatingPostRequestMessage();

            if (data.hasOwnProperty('ratings')) {
                obj['ratings'] = ApiClient.convertToType(data['ratings'], [Rating]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RatingPostRequestMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RatingPostRequestMessage</code>.
     */
    static validateJSON(data) {
        if (data['ratings']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['ratings'])) {
                throw new Error("Expected the field `ratings` to be an array in the JSON data but got " + data['ratings']);
            }
            // validate the optional field `ratings` (array)
            for (const item of data['ratings']) {
                Rating.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Rating>} ratings
 */
RatingPostRequestMessage.prototype['ratings'] = undefined;






export default RatingPostRequestMessage;

