/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MediaFile from './MediaFile';
import State from './State';
import Time from './Time';

/**
 * The ReplacementTerm model module.
 * @module model/ReplacementTerm
 * @version 1.1.0
 */
class ReplacementTerm {
    /**
     * Constructs a new <code>ReplacementTerm</code>.
     * The replacement policy of an item or an order
     * @alias module:model/ReplacementTerm
     */
    constructor() { 
        
        ReplacementTerm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReplacementTerm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReplacementTerm} obj Optional instance to populate.
     * @return {module:model/ReplacementTerm} The populated <code>ReplacementTerm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReplacementTerm();

            if (data.hasOwnProperty('fulfillment_state')) {
                obj['fulfillment_state'] = ApiClient.convertToType(data['fulfillment_state'], State);
            }
            if (data.hasOwnProperty('replace_within')) {
                obj['replace_within'] = ApiClient.convertToType(data['replace_within'], Time);
            }
            if (data.hasOwnProperty('external_ref')) {
                obj['external_ref'] = MediaFile.constructFromObject(data['external_ref']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReplacementTerm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReplacementTerm</code>.
     */
    static validateJSON(data) {
        // validate the optional field `fulfillment_state`
        if (data['fulfillment_state']) { // data not null
          State.validateJSON(data['fulfillment_state']);
        }
        // validate the optional field `replace_within`
        if (data['replace_within']) { // data not null
          Time.validateJSON(data['replace_within']);
        }
        // validate the optional field `external_ref`
        if (data['external_ref']) { // data not null
          MediaFile.validateJSON(data['external_ref']);
        }

        return true;
    }


}



/**
 * @member {module:model/State} fulfillment_state
 */
ReplacementTerm.prototype['fulfillment_state'] = undefined;

/**
 * @member {module:model/Time} replace_within
 */
ReplacementTerm.prototype['replace_within'] = undefined;

/**
 * @member {module:model/MediaFile} external_ref
 */
ReplacementTerm.prototype['external_ref'] = undefined;






export default ReplacementTerm;

