/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Ack from './Ack';
import TagGroup from './TagGroup';

/**
 * The SearchPost200ResponseMessageAck model module.
 * @module model/SearchPost200ResponseMessageAck
 * @version 1.1.0
 */
class SearchPost200ResponseMessageAck {
    /**
     * Constructs a new <code>SearchPost200ResponseMessageAck</code>.
     * @alias module:model/SearchPost200ResponseMessageAck
     * @implements module:model/Ack
     */
    constructor() { 
        Ack.initialize(this);
        SearchPost200ResponseMessageAck.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchPost200ResponseMessageAck</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchPost200ResponseMessageAck} obj Optional instance to populate.
     * @return {module:model/SearchPost200ResponseMessageAck} The populated <code>SearchPost200ResponseMessageAck</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchPost200ResponseMessageAck();
            Ack.constructFromObject(data, obj);

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('tags')) {
                obj['tags'] = ApiClient.convertToType(data['tags'], [TagGroup]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchPost200ResponseMessageAck</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchPost200ResponseMessageAck</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        if (data['tags']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['tags'])) {
                throw new Error("Expected the field `tags` to be an array in the JSON data but got " + data['tags']);
            }
            // validate the optional field `tags` (array)
            for (const item of data['tags']) {
                TagGroup.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/SearchPost200ResponseMessageAck.StatusEnum} status
 */
SearchPost200ResponseMessageAck.prototype['status'] = undefined;

/**
 * A list of tags containing any additional information sent along with the Acknowledgement.
 * @member {Array.<module:model/TagGroup>} tags
 */
SearchPost200ResponseMessageAck.prototype['tags'] = undefined;


// Implement Ack interface:
/**
 * The status of the acknowledgement. If the request passes the validation criteria of the BPP, then this is set to ACK. If a BPP responds with status = `ACK` to a request, it is required to respond with a callback. If the request fails the validation criteria, then this is set to NACK. Additionally, if a BPP does not intend to respond with a callback even after the request meets the validation criteria, it should set this value to `NACK`.
 * @member {module:model/Ack.StatusEnum} status
 */
Ack.prototype['status'] = undefined;
/**
 * A list of tags containing any additional information sent along with the Acknowledgement.
 * @member {Array.<module:model/TagGroup>} tags
 */
Ack.prototype['tags'] = undefined;



/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
SearchPost200ResponseMessageAck['StatusEnum'] = {

    /**
     * value: "ACK"
     * @const
     */
    "ACK": "ACK",

    /**
     * value: "NACK"
     * @const
     */
    "NACK": "NACK"
};



export default SearchPost200ResponseMessageAck;

