/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Intent from './Intent';

/**
 * The SearchPostRequestMessage model module.
 * @module model/SearchPostRequestMessage
 * @version 1.1.0
 */
class SearchPostRequestMessage {
    /**
     * Constructs a new <code>SearchPostRequestMessage</code>.
     * @alias module:model/SearchPostRequestMessage
     */
    constructor() { 
        
        SearchPostRequestMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchPostRequestMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchPostRequestMessage} obj Optional instance to populate.
     * @return {module:model/SearchPostRequestMessage} The populated <code>SearchPostRequestMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchPostRequestMessage();

            if (data.hasOwnProperty('intent')) {
                obj['intent'] = Intent.constructFromObject(data['intent']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchPostRequestMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchPostRequestMessage</code>.
     */
    static validateJSON(data) {
        // validate the optional field `intent`
        if (data['intent']) { // data not null
          Intent.validateJSON(data['intent']);
        }

        return true;
    }


}



/**
 * @member {module:model/Intent} intent
 */
SearchPostRequestMessage.prototype['intent'] = undefined;






export default SearchPostRequestMessage;

