/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Id from './Id';

/**
 * The StatusPostRequestMessage model module.
 * @module model/StatusPostRequestMessage
 * @version 1.1.0
 */
class StatusPostRequestMessage {
    /**
     * Constructs a new <code>StatusPostRequestMessage</code>.
     * @alias module:model/StatusPostRequestMessage
     * @param orderId {module:model/Id} 
     */
    constructor(orderId) { 
        
        StatusPostRequestMessage.initialize(this, orderId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, orderId) { 
        obj['order_id'] = orderId;
    }

    /**
     * Constructs a <code>StatusPostRequestMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StatusPostRequestMessage} obj Optional instance to populate.
     * @return {module:model/StatusPostRequestMessage} The populated <code>StatusPostRequestMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatusPostRequestMessage();

            if (data.hasOwnProperty('order_id')) {
                obj['order_id'] = Id.constructFromObject(data['order_id']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StatusPostRequestMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StatusPostRequestMessage</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StatusPostRequestMessage.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

StatusPostRequestMessage.RequiredProperties = ["order_id"];

/**
 * @member {module:model/Id} order_id
 */
StatusPostRequestMessage.prototype['order_id'] = undefined;






export default StatusPostRequestMessage;

