/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SupportPostRequestContext from './SupportPostRequestContext';
import SupportPostRequestMessage from './SupportPostRequestMessage';

/**
 * The SupportPostRequest model module.
 * @module model/SupportPostRequest
 * @version 1.1.0
 */
class SupportPostRequest {
    /**
     * Constructs a new <code>SupportPostRequest</code>.
     * @alias module:model/SupportPostRequest
     * @param context {module:model/SupportPostRequestContext} 
     * @param message {module:model/SupportPostRequestMessage} 
     */
    constructor(context, message) { 
        
        SupportPostRequest.initialize(this, context, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, context, message) { 
        obj['context'] = context;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>SupportPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SupportPostRequest} obj Optional instance to populate.
     * @return {module:model/SupportPostRequest} The populated <code>SupportPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SupportPostRequest();

            if (data.hasOwnProperty('context')) {
                obj['context'] = SupportPostRequestContext.constructFromObject(data['context']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = SupportPostRequestMessage.constructFromObject(data['message']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SupportPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SupportPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SupportPostRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `context`
        if (data['context']) { // data not null
          SupportPostRequestContext.validateJSON(data['context']);
        }
        // validate the optional field `message`
        if (data['message']) { // data not null
          SupportPostRequestMessage.validateJSON(data['message']);
        }

        return true;
    }


}

SupportPostRequest.RequiredProperties = ["context", "message"];

/**
 * @member {module:model/SupportPostRequestContext} context
 */
SupportPostRequest.prototype['context'] = undefined;

/**
 * @member {module:model/SupportPostRequestMessage} message
 */
SupportPostRequest.prototype['message'] = undefined;






export default SupportPostRequest;

