/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Support from './Support';

/**
 * The SupportPostRequestMessage model module.
 * @module model/SupportPostRequestMessage
 * @version 1.1.0
 */
class SupportPostRequestMessage {
    /**
     * Constructs a new <code>SupportPostRequestMessage</code>.
     * @alias module:model/SupportPostRequestMessage
     */
    constructor() { 
        
        SupportPostRequestMessage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SupportPostRequestMessage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SupportPostRequestMessage} obj Optional instance to populate.
     * @return {module:model/SupportPostRequestMessage} The populated <code>SupportPostRequestMessage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SupportPostRequestMessage();

            if (data.hasOwnProperty('support')) {
                obj['support'] = Support.constructFromObject(data['support']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SupportPostRequestMessage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SupportPostRequestMessage</code>.
     */
    static validateJSON(data) {
        // validate the optional field `support`
        if (data['support']) { // data not null
          Support.validateJSON(data['support']);
        }

        return true;
    }


}



/**
 * @member {module:model/Support} support
 */
SupportPostRequestMessage.prototype['support'] = undefined;






export default SupportPostRequestMessage;

