/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// BecknApplicationPlatformBAPAPIService is a service that implements the logic for the BecknApplicationPlatformBAPAPIServicer
// This service should implement the business logic for every endpoint for the BecknApplicationPlatformBAPAPI API.
// Include any external packages or services that will be required by this service.
type BecknApplicationPlatformBAPAPIService struct {
}

// NewBecknApplicationPlatformBAPAPIService creates a default api service
func NewBecknApplicationPlatformBAPAPIService() BecknApplicationPlatformBAPAPIServicer {
	return &BecknApplicationPlatformBAPAPIService{}
}

// OnCancelPost - 
func (s *BecknApplicationPlatformBAPAPIService) OnCancelPost(ctx context.Context, onCancelPostRequest OnCancelPostRequest) (ImplResponse, error) {
	// TODO - update OnCancelPost with the required logic for this service method.
	// Add api_beckn_application_platform_bap_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OnSearchPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, OnSearchPost200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OnCancelPost method not implemented")
}

// OnConfirmPost - 
func (s *BecknApplicationPlatformBAPAPIService) OnConfirmPost(ctx context.Context, onConfirmPostRequest OnConfirmPostRequest) (ImplResponse, error) {
	// TODO - update OnConfirmPost with the required logic for this service method.
	// Add api_beckn_application_platform_bap_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OnSearchPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, OnSearchPost200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OnConfirmPost method not implemented")
}

// OnInitPost - 
func (s *BecknApplicationPlatformBAPAPIService) OnInitPost(ctx context.Context, onInitPostRequest OnInitPostRequest) (ImplResponse, error) {
	// TODO - update OnInitPost with the required logic for this service method.
	// Add api_beckn_application_platform_bap_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OnSearchPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, OnSearchPost200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OnInitPost method not implemented")
}

// OnRatingPost - 
func (s *BecknApplicationPlatformBAPAPIService) OnRatingPost(ctx context.Context, onRatingPostRequest OnRatingPostRequest) (ImplResponse, error) {
	// TODO - update OnRatingPost with the required logic for this service method.
	// Add api_beckn_application_platform_bap_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OnSearchPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, OnSearchPost200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OnRatingPost method not implemented")
}

// OnSearchPost - 
func (s *BecknApplicationPlatformBAPAPIService) OnSearchPost(ctx context.Context, onSearchPostRequest OnSearchPostRequest) (ImplResponse, error) {
	// TODO - update OnSearchPost with the required logic for this service method.
	// Add api_beckn_application_platform_bap_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OnSearchPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, OnSearchPost200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OnSearchPost method not implemented")
}

// OnSelectPost - 
func (s *BecknApplicationPlatformBAPAPIService) OnSelectPost(ctx context.Context, onSelectPostRequest OnSelectPostRequest) (ImplResponse, error) {
	// TODO - update OnSelectPost with the required logic for this service method.
	// Add api_beckn_application_platform_bap_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OnSearchPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, OnSearchPost200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OnSelectPost method not implemented")
}

// OnStatusPost - 
func (s *BecknApplicationPlatformBAPAPIService) OnStatusPost(ctx context.Context, onStatusPostRequest OnStatusPostRequest) (ImplResponse, error) {
	// TODO - update OnStatusPost with the required logic for this service method.
	// Add api_beckn_application_platform_bap_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OnSearchPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, OnSearchPost200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OnStatusPost method not implemented")
}

// OnSupportPost - 
func (s *BecknApplicationPlatformBAPAPIService) OnSupportPost(ctx context.Context, onSupportPostRequest OnSupportPostRequest) (ImplResponse, error) {
	// TODO - update OnSupportPost with the required logic for this service method.
	// Add api_beckn_application_platform_bap_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OnSearchPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, OnSearchPost200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OnSupportPost method not implemented")
}

// OnUpdatePost - 
func (s *BecknApplicationPlatformBAPAPIService) OnUpdatePost(ctx context.Context, onUpdatePostRequest OnUpdatePostRequest) (ImplResponse, error) {
	// TODO - update OnUpdatePost with the required logic for this service method.
	// Add api_beckn_application_platform_bap_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OnSearchPost200Response{}) or use other options such as http.Ok ...
	// return Response(200, OnSearchPost200Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("OnUpdatePost method not implemented")
}
