/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// AddOn - Describes an additional item offered as a value-addition to a product or service. This does not exist independently in a catalog and is always associated with an item.
type AddOn struct {

	// Provider-defined ID of the add-on
	Id string `json:"id,omitempty"`

	Descriptor Descriptor `json:"descriptor,omitempty"`

	Price Price `json:"price,omitempty"`
}

// AssertAddOnRequired checks if the required fields are not zero-ed
func AssertAddOnRequired(obj AddOn) error {
	if err := AssertDescriptorRequired(obj.Descriptor); err != nil {
		return err
	}
	if err := AssertPriceRequired(obj.Price); err != nil {
		return err
	}
	return nil
}

// AssertAddOnConstraints checks if the values respects the defined constraints
func AssertAddOnConstraints(obj AddOn) error {
	return nil
}
