/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Vehicle - Describes a vehicle is a device that is designed or used to transport people or cargo over land, water, air, or through space.<br>This has properties like category, capacity, make, model, size,variant,color,energy_type,registration
type Vehicle struct {

	Category string `json:"category,omitempty"`

	Capacity int32 `json:"capacity,omitempty"`

	Make string `json:"make,omitempty"`

	Model string `json:"model,omitempty"`

	Size string `json:"size,omitempty"`

	Variant string `json:"variant,omitempty"`

	Color string `json:"color,omitempty"`

	EnergyType string `json:"energy_type,omitempty"`

	Registration string `json:"registration,omitempty"`

	WheelsCount string `json:"wheels_count,omitempty"`

	CargoVolumne string `json:"cargo_volumne,omitempty"`

	WheelchairAccess string `json:"wheelchair_access,omitempty"`

	Code string `json:"code,omitempty"`

	EmissionStandard string `json:"emission_standard,omitempty"`
}

// AssertVehicleRequired checks if the required fields are not zero-ed
func AssertVehicleRequired(obj Vehicle) error {
	return nil
}

// AssertVehicleConstraints checks if the values respects the defined constraints
func AssertVehicleConstraints(obj Vehicle) error {
	return nil
}
