/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ItemRefundTermsInner - Refund term of an item or an order
type ItemRefundTermsInner struct {

	FulfillmentState State `json:"fulfillment_state,omitempty"`

	// Indicates if cancellation will result in a refund
	RefundEligible bool `json:"refund_eligible,omitempty"`

	RefundWithin Time `json:"refund_within,omitempty"`

	RefundAmount Price `json:"refund_amount,omitempty"`
}

// AssertItemRefundTermsInnerRequired checks if the required fields are not zero-ed
func AssertItemRefundTermsInnerRequired(obj ItemRefundTermsInner) error {
	if err := AssertStateRequired(obj.FulfillmentState); err != nil {
		return err
	}
	if err := AssertTimeRequired(obj.RefundWithin); err != nil {
		return err
	}
	if err := AssertPriceRequired(obj.RefundAmount); err != nil {
		return err
	}
	return nil
}

// AssertItemRefundTermsInnerConstraints checks if the values respects the defined constraints
func AssertItemRefundTermsInnerConstraints(obj ItemRefundTermsInner) error {
	return nil
}
