/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Credential - Describes a credential of an entity - Person or Organization
type Credential struct {

	Id string `json:"id,omitempty"`

	Type string `json:"type,omitempty"`

	// URL of the credential
	Url string `json:"url,omitempty"`
}

// AssertCredentialRequired checks if the required fields are not zero-ed
func AssertCredentialRequired(obj Credential) error {
	return nil
}

// AssertCredentialConstraints checks if the values respects the defined constraints
func AssertCredentialConstraints(obj Credential) error {
	return nil
}
