/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type PaymentParams struct {

	// The reference transaction ID associated with a payment activity
	TransactionId string `json:"transaction_id,omitempty"`

	Amount string `json:"amount,omitempty"`

	Currency string `json:"currency,omitempty"`

	BankCode string `json:"bank_code,omitempty"`

	BankAccountNumber string `json:"bank_account_number,omitempty"`

	VirtualPaymentAddress string `json:"virtual_payment_address,omitempty"`

	SourceBankCode string `json:"source_bank_code,omitempty"`

	SourceBankAccountNumber string `json:"source_bank_account_number,omitempty"`

	SourceVirtualPaymentAddress string `json:"source_virtual_payment_address,omitempty"`
}

// AssertPaymentParamsRequired checks if the required fields are not zero-ed
func AssertPaymentParamsRequired(obj PaymentParams) error {
	return nil
}

// AssertPaymentParamsConstraints checks if the values respects the defined constraints
func AssertPaymentParamsConstraints(obj PaymentParams) error {
	return nil
}
