/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// City - Describes a city
type City struct {

	// Name of the city
	Name string `json:"name,omitempty"`

	// City code
	Code string `json:"code,omitempty"`
}

// AssertCityRequired checks if the required fields are not zero-ed
func AssertCityRequired(obj City) error {
	return nil
}

// AssertCityConstraints checks if the values respects the defined constraints
func AssertCityConstraints(obj City) error {
	return nil
}
