/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type OnSearchPostRequestMessage struct {

	Catalog Catalog `json:"catalog"`
}

// AssertOnSearchPostRequestMessageRequired checks if the required fields are not zero-ed
func AssertOnSearchPostRequestMessageRequired(obj OnSearchPostRequestMessage) error {
	elements := map[string]interface{}{
		"catalog": obj.Catalog,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCatalogRequired(obj.Catalog); err != nil {
		return err
	}
	return nil
}

// AssertOnSearchPostRequestMessageConstraints checks if the values respects the defined constraints
func AssertOnSearchPostRequestMessageConstraints(obj OnSearchPostRequestMessage) error {
	return nil
}
