/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Price - Describes the price of a product or service
type Price struct {

	Currency string `json:"currency,omitempty"`

	// Describes a numerical value in decimal form
	Value string `json:"value,omitempty"`

	// Describes a numerical value in decimal form
	EstimatedValue string `json:"estimated_value,omitempty"`

	// Describes a numerical value in decimal form
	ComputedValue string `json:"computed_value,omitempty"`

	// Describes a numerical value in decimal form
	ListedValue string `json:"listed_value,omitempty"`

	// Describes a numerical value in decimal form
	OfferedValue string `json:"offered_value,omitempty"`

	// Describes a numerical value in decimal form
	MinimumValue string `json:"minimum_value,omitempty"`

	// Describes a numerical value in decimal form
	MaximumValue string `json:"maximum_value,omitempty"`
}

// AssertPriceRequired checks if the required fields are not zero-ed
func AssertPriceRequired(obj Price) error {
	return nil
}

// AssertPriceConstraints checks if the values respects the defined constraints
func AssertPriceConstraints(obj Price) error {
	return nil
}
