/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



type TimeRange struct {

	Start time.Time `json:"start,omitempty"`

	End time.Time `json:"end,omitempty"`
}

// AssertTimeRangeRequired checks if the required fields are not zero-ed
func AssertTimeRangeRequired(obj TimeRange) error {
	return nil
}

// AssertTimeRangeConstraints checks if the values respects the defined constraints
func AssertTimeRangeConstraints(obj TimeRange) error {
	return nil
}
