/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Contact - Describes the contact information of an entity
type Contact struct {

	Phone string `json:"phone,omitempty"`

	Email string `json:"email,omitempty"`

	// A Jcard object as per draft-ietf-jcardcal-jcard-03 specification
	Jcard map[string]interface{} `json:"jcard,omitempty"`
}

// AssertContactRequired checks if the required fields are not zero-ed
func AssertContactRequired(obj Contact) error {
	return nil
}

// AssertContactConstraints checks if the values respects the defined constraints
func AssertContactConstraints(obj Contact) error {
	return nil
}
