/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// CancellationTerm - Describes the cancellation terms of an item or an order. This can be referenced at an item or order level. Item-level cancellation terms can override the terms at the order level.
type CancellationTerm struct {

	FulfillmentState FulfillmentState `json:"fulfillment_state,omitempty"`

	// Indicates whether a reason is required to cancel the order
	ReasonRequired bool `json:"reason_required,omitempty"`

	CancelBy Time `json:"cancel_by,omitempty"`

	CancellationFee Fee `json:"cancellation_fee,omitempty"`

	Xinput XInput `json:"xinput,omitempty"`

	ExternalRef MediaFile `json:"external_ref,omitempty"`
}

// AssertCancellationTermRequired checks if the required fields are not zero-ed
func AssertCancellationTermRequired(obj CancellationTerm) error {
	if err := AssertFulfillmentStateRequired(obj.FulfillmentState); err != nil {
		return err
	}
	if err := AssertTimeRequired(obj.CancelBy); err != nil {
		return err
	}
	if err := AssertFeeRequired(obj.CancellationFee); err != nil {
		return err
	}
	if err := AssertXInputRequired(obj.Xinput); err != nil {
		return err
	}
	if err := AssertMediaFileRequired(obj.ExternalRef); err != nil {
		return err
	}
	return nil
}

// AssertCancellationTermConstraints checks if the values respects the defined constraints
func AssertCancellationTermConstraints(obj CancellationTerm) error {
	return nil
}
