/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// TagGroup - A collection of tag objects with group level attributes. For detailed documentation on the Tags and Tag Groups schema go to https://github.com/beckn/protocol-specifications/discussions/316
type TagGroup struct {

	// Indicates the display properties of the tag group. If display is set to false, then the group will not be displayed. If it is set to true, it should be displayed. However, group-level display properties can be overriden by individual tag-level display property. As this schema is purely for catalog display purposes, it is not recommended to send this value during search.
	Display bool `json:"display,omitempty"`

	Descriptor Descriptor `json:"descriptor,omitempty"`

	// An array of Tag objects listed under this group. This property can be set by BAPs during search to narrow the `search` and achieve more relevant results. When received during `on_search`, BAPs must render this list under the heading described by the `name` property of this schema.
	List []Tag `json:"list,omitempty"`
}

// AssertTagGroupRequired checks if the required fields are not zero-ed
func AssertTagGroupRequired(obj TagGroup) error {
	if err := AssertDescriptorRequired(obj.Descriptor); err != nil {
		return err
	}
	for _, el := range obj.List {
		if err := AssertTagRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTagGroupConstraints checks if the values respects the defined constraints
func AssertTagGroupConstraints(obj TagGroup) error {
	return nil
}
