/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ReplacementTerm - The replacement policy of an item or an order
type ReplacementTerm struct {

	FulfillmentState State `json:"fulfillment_state,omitempty"`

	ReplaceWithin Time `json:"replace_within,omitempty"`

	ExternalRef MediaFile `json:"external_ref,omitempty"`
}

// AssertReplacementTermRequired checks if the required fields are not zero-ed
func AssertReplacementTermRequired(obj ReplacementTerm) error {
	if err := AssertStateRequired(obj.FulfillmentState); err != nil {
		return err
	}
	if err := AssertTimeRequired(obj.ReplaceWithin); err != nil {
		return err
	}
	if err := AssertMediaFileRequired(obj.ExternalRef); err != nil {
		return err
	}
	return nil
}

// AssertReplacementTermConstraints checks if the values respects the defined constraints
func AssertReplacementTermConstraints(obj ReplacementTerm) error {
	return nil
}
