/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type OnSelectPostRequestMessage struct {

	Order Order `json:"order,omitempty"`
}

// AssertOnSelectPostRequestMessageRequired checks if the required fields are not zero-ed
func AssertOnSelectPostRequestMessageRequired(obj OnSelectPostRequestMessage) error {
	if err := AssertOrderRequired(obj.Order); err != nil {
		return err
	}
	return nil
}

// AssertOnSelectPostRequestMessageConstraints checks if the values respects the defined constraints
func AssertOnSelectPostRequestMessageConstraints(obj OnSelectPostRequestMessage) error {
	return nil
}
