/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Quotation - Describes a quote. It is the estimated price of products or services from the BPP.<br>This has properties like price, breakup, ttl
type Quotation struct {

	// ID of the quote.
	Id string `json:"id,omitempty"`

	Price Price `json:"price,omitempty"`

	// the breakup of the total quoted price
	Breakup []QuotationBreakupInner `json:"breakup,omitempty"`

	// Describes duration as per ISO8601 format
	Ttl string `json:"ttl,omitempty"`
}

// AssertQuotationRequired checks if the required fields are not zero-ed
func AssertQuotationRequired(obj Quotation) error {
	if err := AssertPriceRequired(obj.Price); err != nil {
		return err
	}
	for _, el := range obj.Breakup {
		if err := AssertQuotationBreakupInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertQuotationConstraints checks if the values respects the defined constraints
func AssertQuotationConstraints(obj Quotation) error {
	return nil
}
