/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



// FulfillmentState - Describes the state of fulfillment
type FulfillmentState struct {

	Descriptor Descriptor `json:"descriptor,omitempty"`

	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// ID of entity which changed the state
	UpdatedBy string `json:"updated_by,omitempty"`
}

// AssertFulfillmentStateRequired checks if the required fields are not zero-ed
func AssertFulfillmentStateRequired(obj FulfillmentState) error {
	if err := AssertDescriptorRequired(obj.Descriptor); err != nil {
		return err
	}
	return nil
}

// AssertFulfillmentStateConstraints checks if the values respects the defined constraints
func AssertFulfillmentStateConstraints(obj FulfillmentState) error {
	return nil
}
