/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Support - Details of customer support
type Support struct {

	RefId string `json:"ref_id,omitempty"`

	CallbackPhone string `json:"callback_phone,omitempty"`

	Phone string `json:"phone,omitempty"`

	Email string `json:"email,omitempty"`

	Url string `json:"url,omitempty"`
}

// AssertSupportRequired checks if the required fields are not zero-ed
func AssertSupportRequired(obj Support) error {
	return nil
}

// AssertSupportConstraints checks if the values respects the defined constraints
func AssertSupportConstraints(obj Support) error {
	return nil
}
