/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Billing - Describes the billing details of an entity.<br>This has properties like name,organization,address,email,phone,time,tax_number, created_at,updated_at
type Billing struct {

	// Name of the billable entity
	Name string `json:"name,omitempty"`

	Organization Organization `json:"organization,omitempty"`

	// Describes a postal address.
	Address string `json:"address,omitempty"`

	State State `json:"state,omitempty"`

	City City `json:"city,omitempty"`

	// Email address where the bill is sent to
	Email string `json:"email,omitempty"`

	// Phone number of the billable entity
	Phone string `json:"phone,omitempty"`

	Time Time `json:"time,omitempty"`

	// ID of the billable entity as recognized by the taxation authority
	TaxId string `json:"tax_id,omitempty"`
}

// AssertBillingRequired checks if the required fields are not zero-ed
func AssertBillingRequired(obj Billing) error {
	if err := AssertOrganizationRequired(obj.Organization); err != nil {
		return err
	}
	if err := AssertStateRequired(obj.State); err != nil {
		return err
	}
	if err := AssertCityRequired(obj.City); err != nil {
		return err
	}
	if err := AssertTimeRequired(obj.Time); err != nil {
		return err
	}
	return nil
}

// AssertBillingConstraints checks if the values respects the defined constraints
func AssertBillingConstraints(obj Billing) error {
	return nil
}
