/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Circle - Describes a circular region of a specified radius centered at a specified GPS coordinate.
type Circle struct {

	// Describes a GPS coordinate
	Gps string `json:"gps,omitempty"`

	Radius Scalar `json:"radius,omitempty"`
}

// AssertCircleRequired checks if the required fields are not zero-ed
func AssertCircleRequired(obj Circle) error {
	if err := AssertScalarRequired(obj.Radius); err != nil {
		return err
	}
	return nil
}

// AssertCircleConstraints checks if the values respects the defined constraints
func AssertCircleConstraints(obj Circle) error {
	return nil
}
