/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Stop - A logical point in space and time during the fulfillment of an order.
type Stop struct {

	Id string `json:"id,omitempty"`

	ParentStopId string `json:"parent_stop_id,omitempty"`

	Location Location `json:"location,omitempty"`

	// The type of stop. Allowed values of this property can be defined by the network policy.
	Type string `json:"type,omitempty"`

	Time Time `json:"time,omitempty"`

	Instructions Descriptor `json:"instructions,omitempty"`

	Contact Contact `json:"contact,omitempty"`

	Person Person `json:"person,omitempty"`

	Authorization Authorization `json:"authorization,omitempty"`
}

// AssertStopRequired checks if the required fields are not zero-ed
func AssertStopRequired(obj Stop) error {
	if err := AssertLocationRequired(obj.Location); err != nil {
		return err
	}
	if err := AssertTimeRequired(obj.Time); err != nil {
		return err
	}
	if err := AssertDescriptorRequired(obj.Instructions); err != nil {
		return err
	}
	if err := AssertContactRequired(obj.Contact); err != nil {
		return err
	}
	if err := AssertPersonRequired(obj.Person); err != nil {
		return err
	}
	if err := AssertAuthorizationRequired(obj.Authorization); err != nil {
		return err
	}
	return nil
}

// AssertStopConstraints checks if the values respects the defined constraints
func AssertStopConstraints(obj Stop) error {
	return nil
}
