/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Offer - An offer associated with a catalog. This is typically used to promote a particular product and enable more purchases.
type Offer struct {

	Id string `json:"id,omitempty"`

	Descriptor Descriptor `json:"descriptor,omitempty"`

	LocationIds []Id `json:"location_ids,omitempty"`

	CategoryIds []Id `json:"category_ids,omitempty"`

	ItemIds []Id `json:"item_ids,omitempty"`

	Time Time `json:"time,omitempty"`

	Tags []TagGroup `json:"tags,omitempty"`
}

// AssertOfferRequired checks if the required fields are not zero-ed
func AssertOfferRequired(obj Offer) error {
	if err := AssertDescriptorRequired(obj.Descriptor); err != nil {
		return err
	}
	if err := AssertTimeRequired(obj.Time); err != nil {
		return err
	}
	for _, el := range obj.Tags {
		if err := AssertTagGroupRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertOfferConstraints checks if the values respects the defined constraints
func AssertOfferConstraints(obj Offer) error {
	return nil
}
