/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Descriptor - Physical description of something.
type Descriptor struct {

	Name string `json:"name,omitempty"`

	Code string `json:"code,omitempty"`

	ShortDesc string `json:"short_desc,omitempty"`

	LongDesc string `json:"long_desc,omitempty"`

	AdditionalDesc DescriptorAdditionalDesc `json:"additional_desc,omitempty"`

	Media []MediaFile `json:"media,omitempty"`

	Images []Image `json:"images,omitempty"`
}

// AssertDescriptorRequired checks if the required fields are not zero-ed
func AssertDescriptorRequired(obj Descriptor) error {
	if err := AssertDescriptorAdditionalDescRequired(obj.AdditionalDesc); err != nil {
		return err
	}
	for _, el := range obj.Media {
		if err := AssertMediaFileRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Images {
		if err := AssertImageRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertDescriptorConstraints checks if the values respects the defined constraints
func AssertDescriptorConstraints(obj Descriptor) error {
	return nil
}
