/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type OnInitPostRequestMessage struct {

	Order Order `json:"order"`
}

// AssertOnInitPostRequestMessageRequired checks if the required fields are not zero-ed
func AssertOnInitPostRequestMessageRequired(obj OnInitPostRequestMessage) error {
	elements := map[string]interface{}{
		"order": obj.Order,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertOrderRequired(obj.Order); err != nil {
		return err
	}
	return nil
}

// AssertOnInitPostRequestMessageConstraints checks if the values respects the defined constraints
func AssertOnInitPostRequestMessageConstraints(obj OnInitPostRequestMessage) error {
	return nil
}
