/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"errors"
)



// ItemQuantitySelected - This represents the quantity selected for purchase of the item
type ItemQuantitySelected struct {

	Count int32 `json:"count,omitempty"`

	Measure Scalar `json:"measure,omitempty"`
}

// AssertItemQuantitySelectedRequired checks if the required fields are not zero-ed
func AssertItemQuantitySelectedRequired(obj ItemQuantitySelected) error {
	if err := AssertScalarRequired(obj.Measure); err != nil {
		return err
	}
	return nil
}

// AssertItemQuantitySelectedConstraints checks if the values respects the defined constraints
func AssertItemQuantitySelectedConstraints(obj ItemQuantitySelected) error {
	if obj.Count < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
