/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Fee - A fee applied on a particular entity
type Fee struct {

	// Describes a numerical value in decimal form
	Percentage string `json:"percentage,omitempty"`

	Amount Price `json:"amount,omitempty"`
}

// AssertFeeRequired checks if the required fields are not zero-ed
func AssertFeeRequired(obj Fee) error {
	if err := AssertPriceRequired(obj.Amount); err != nil {
		return err
	}
	return nil
}

// AssertFeeConstraints checks if the values respects the defined constraints
func AssertFeeConstraints(obj Fee) error {
	return nil
}
