/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"time"
)



// Time - Describes time in its various forms. It can be a single point in time; duration; or a structured timetable of operations<br>This has properties like label, time stamp,duration,range, days, schedule
type Time struct {

	Label string `json:"label,omitempty"`

	Timestamp time.Time `json:"timestamp,omitempty"`

	// Describes duration as per ISO8601 format
	Duration string `json:"duration,omitempty"`

	Range TimeRange `json:"range,omitempty"`

	// comma separated values representing days of the week
	Days string `json:"days,omitempty"`

	Schedule Schedule `json:"schedule,omitempty"`
}

// AssertTimeRequired checks if the required fields are not zero-ed
func AssertTimeRequired(obj Time) error {
	if err := AssertTimeRangeRequired(obj.Range); err != nil {
		return err
	}
	if err := AssertScheduleRequired(obj.Schedule); err != nil {
		return err
	}
	return nil
}

// AssertTimeConstraints checks if the values respects the defined constraints
func AssertTimeConstraints(obj Time) error {
	return nil
}
