/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Category - A label under which a collection of items can be grouped.
type Category struct {

	// ID of the category
	Id string `json:"id,omitempty"`

	ParentCategoryId Id `json:"parent_category_id,omitempty"`

	Descriptor Descriptor `json:"descriptor,omitempty"`

	Time Time `json:"time,omitempty"`

	// Time to live for an instance of this schema
	Ttl *interface{} `json:"ttl,omitempty"`

	Tags []TagGroup `json:"tags,omitempty"`
}

// AssertCategoryRequired checks if the required fields are not zero-ed
func AssertCategoryRequired(obj Category) error {
	if err := AssertDescriptorRequired(obj.Descriptor); err != nil {
		return err
	}
	if err := AssertTimeRequired(obj.Time); err != nil {
		return err
	}
	for _, el := range obj.Tags {
		if err := AssertTagGroupRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCategoryConstraints checks if the values respects the defined constraints
func AssertCategoryConstraints(obj Category) error {
	return nil
}
