/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type OnSupportPostRequest struct {

	Context OnSupportPostRequestContext `json:"context"`

	Message OnSupportPostRequestMessage `json:"message,omitempty"`

	Error Error `json:"error,omitempty"`
}

// AssertOnSupportPostRequestRequired checks if the required fields are not zero-ed
func AssertOnSupportPostRequestRequired(obj OnSupportPostRequest) error {
	elements := map[string]interface{}{
		"context": obj.Context,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertOnSupportPostRequestContextRequired(obj.Context); err != nil {
		return err
	}
	if err := AssertOnSupportPostRequestMessageRequired(obj.Message); err != nil {
		return err
	}
	if err := AssertErrorRequired(obj.Error); err != nil {
		return err
	}
	return nil
}

// AssertOnSupportPostRequestConstraints checks if the values respects the defined constraints
func AssertOnSupportPostRequestConstraints(obj OnSupportPostRequest) error {
	return nil
}
