/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// Tracking - Contains tracking information that can be used by the BAP to track the fulfillment of an order in real-time. which is useful for knowing the location of time sensitive deliveries.
type Tracking struct {

	// A unique tracking reference number
	Id string `json:"id,omitempty"`

	// A URL to the tracking endpoint. This can be a link to a tracking webpage, a webhook URL created by the BAP where BPP can push the tracking data, or a GET url creaed by the BPP which the BAP can poll to get the tracking data. It can also be a websocket URL where the BPP can push real-time tracking data.
	Url string `json:"url,omitempty"`

	Location Location `json:"location,omitempty"`

	// This value indicates if the tracking is currently active or not. If this value is `active`, then the BAP can begin tracking the order. If this value is `inactive`, the tracking URL is considered to be expired and the BAP should stop tracking the order.
	Status string `json:"status,omitempty"`
}

// AssertTrackingRequired checks if the required fields are not zero-ed
func AssertTrackingRequired(obj Tracking) error {
	if err := AssertLocationRequired(obj.Location); err != nil {
		return err
	}
	return nil
}

// AssertTrackingConstraints checks if the values respects the defined constraints
func AssertTrackingConstraints(obj Tracking) error {
	return nil
}
