/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




// ReturnTerm - Describes the return policy of an item or an order
type ReturnTerm struct {

	FulfillmentState State `json:"fulfillment_state,omitempty"`

	// Indicates whether the item is eligible for return
	ReturnEligible bool `json:"return_eligible,omitempty"`

	ReturnTime Time `json:"return_time,omitempty"`

	ReturnLocation Location `json:"return_location,omitempty"`

	// The entity that will perform the return
	FulfillmentManagedBy string `json:"fulfillment_managed_by,omitempty"`
}

// AssertReturnTermRequired checks if the required fields are not zero-ed
func AssertReturnTermRequired(obj ReturnTerm) error {
	if err := AssertStateRequired(obj.FulfillmentState); err != nil {
		return err
	}
	if err := AssertTimeRequired(obj.ReturnTime); err != nil {
		return err
	}
	if err := AssertLocationRequired(obj.ReturnLocation); err != nil {
		return err
	}
	return nil
}

// AssertReturnTermConstraints checks if the values respects the defined constraints
func AssertReturnTermConstraints(obj ReturnTerm) error {
	return nil
}
