/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BecknOdrApiSpecification);
  }
}(this, function(expect, BecknOdrApiSpecification) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BecknOdrApiSpecification.BecknApplicationPlatformBAPApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BecknApplicationPlatformBAPApi', function() {
    describe('cancelPost', function() {
      it('should call cancelPost successfully', function(done) {
        //uncomment below and update the code to test cancelPost
        //instance.cancelPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('confirmPost', function() {
      it('should call confirmPost successfully', function(done) {
        //uncomment below and update the code to test confirmPost
        //instance.confirmPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('initPost', function() {
      it('should call initPost successfully', function(done) {
        //uncomment below and update the code to test initPost
        //instance.initPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('ratingPost', function() {
      it('should call ratingPost successfully', function(done) {
        //uncomment below and update the code to test ratingPost
        //instance.ratingPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchPost', function() {
      it('should call searchPost successfully', function(done) {
        //uncomment below and update the code to test searchPost
        //instance.searchPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selectPost', function() {
      it('should call selectPost successfully', function(done) {
        //uncomment below and update the code to test selectPost
        //instance.selectPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('statusPost', function() {
      it('should call statusPost successfully', function(done) {
        //uncomment below and update the code to test statusPost
        //instance.statusPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('supportPost', function() {
      it('should call supportPost successfully', function(done) {
        //uncomment below and update the code to test supportPost
        //instance.supportPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updatePost', function() {
      it('should call updatePost successfully', function(done) {
        //uncomment below and update the code to test updatePost
        //instance.updatePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
