/*
 * Beckn ODR API Specification
 *
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	BecknApplicationPlatformBAPAPIService := openapi.NewBecknApplicationPlatformBAPAPIService()
	BecknApplicationPlatformBAPAPIController := openapi.NewBecknApplicationPlatformBAPAPIController(BecknApplicationPlatformBAPAPIService)

	router := openapi.NewRouter(BecknApplicationPlatformBAPAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
