/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BecknOdrApiSpecification);
  }
}(this, function(expect, BecknOdrApiSpecification) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BecknOdrApiSpecification.Fulfillment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Fulfillment', function() {
    it('should create an instance of Fulfillment', function() {
      // uncomment below and update the code to test Fulfillment
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be.a(BecknOdrApiSpecification.Fulfillment);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property rateable (base name: "rateable")', function() {
      // uncomment below and update the code to test the property rateable
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property rating (base name: "rating")', function() {
      // uncomment below and update the code to test the property rating
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property tracking (base name: "tracking")', function() {
      // uncomment below and update the code to test the property tracking
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property customer (base name: "customer")', function() {
      // uncomment below and update the code to test the property customer
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property agent (base name: "agent")', function() {
      // uncomment below and update the code to test the property agent
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property contact (base name: "contact")', function() {
      // uncomment below and update the code to test the property contact
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property vehicle (base name: "vehicle")', function() {
      // uncomment below and update the code to test the property vehicle
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property stops (base name: "stops")', function() {
      // uncomment below and update the code to test the property stops
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new BecknOdrApiSpecification.Fulfillment();
      //expect(instance).to.be();
    });

  });

}));
