/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BecknOdrApiSpecification);
  }
}(this, function(expect, BecknOdrApiSpecification) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BecknOdrApiSpecification.Item();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Item', function() {
    it('should create an instance of Item', function() {
      // uncomment below and update the code to test Item
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be.a(BecknOdrApiSpecification.Item);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property parentItemId (base name: "parent_item_id")', function() {
      // uncomment below and update the code to test the property parentItemId
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property parentItemQuantity (base name: "parent_item_quantity")', function() {
      // uncomment below and update the code to test the property parentItemQuantity
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property descriptor (base name: "descriptor")', function() {
      // uncomment below and update the code to test the property descriptor
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property creator (base name: "creator")', function() {
      // uncomment below and update the code to test the property creator
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property price (base name: "price")', function() {
      // uncomment below and update the code to test the property price
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property categoryIds (base name: "category_ids")', function() {
      // uncomment below and update the code to test the property categoryIds
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property fulfillmentIds (base name: "fulfillment_ids")', function() {
      // uncomment below and update the code to test the property fulfillmentIds
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property locationIds (base name: "location_ids")', function() {
      // uncomment below and update the code to test the property locationIds
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property paymentIds (base name: "payment_ids")', function() {
      // uncomment below and update the code to test the property paymentIds
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property addOns (base name: "add_ons")', function() {
      // uncomment below and update the code to test the property addOns
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property cancellationTerms (base name: "cancellation_terms")', function() {
      // uncomment below and update the code to test the property cancellationTerms
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property refundTerms (base name: "refund_terms")', function() {
      // uncomment below and update the code to test the property refundTerms
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property replacementTerms (base name: "replacement_terms")', function() {
      // uncomment below and update the code to test the property replacementTerms
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property returnTerms (base name: "return_terms")', function() {
      // uncomment below and update the code to test the property returnTerms
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property xinput (base name: "xinput")', function() {
      // uncomment below and update the code to test the property xinput
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property time (base name: "time")', function() {
      // uncomment below and update the code to test the property time
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property rateable (base name: "rateable")', function() {
      // uncomment below and update the code to test the property rateable
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property rating (base name: "rating")', function() {
      // uncomment below and update the code to test the property rating
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property matched (base name: "matched")', function() {
      // uncomment below and update the code to test the property matched
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property related (base name: "related")', function() {
      // uncomment below and update the code to test the property related
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property recommended (base name: "recommended")', function() {
      // uncomment below and update the code to test the property recommended
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property ttl (base name: "ttl")', function() {
      // uncomment below and update the code to test the property ttl
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new BecknOdrApiSpecification.Item();
      //expect(instance).to.be();
    });

  });

}));
