/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BecknOdrApiSpecification);
  }
}(this, function(expect, BecknOdrApiSpecification) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BecknOdrApiSpecification.PaymentParams();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentParams', function() {
    it('should create an instance of PaymentParams', function() {
      // uncomment below and update the code to test PaymentParams
      //var instance = new BecknOdrApiSpecification.PaymentParams();
      //expect(instance).to.be.a(BecknOdrApiSpecification.PaymentParams);
    });

    it('should have the property transactionId (base name: "transaction_id")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instance = new BecknOdrApiSpecification.PaymentParams();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new BecknOdrApiSpecification.PaymentParams();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new BecknOdrApiSpecification.PaymentParams();
      //expect(instance).to.be();
    });

    it('should have the property bankCode (base name: "bank_code")', function() {
      // uncomment below and update the code to test the property bankCode
      //var instance = new BecknOdrApiSpecification.PaymentParams();
      //expect(instance).to.be();
    });

    it('should have the property bankAccountNumber (base name: "bank_account_number")', function() {
      // uncomment below and update the code to test the property bankAccountNumber
      //var instance = new BecknOdrApiSpecification.PaymentParams();
      //expect(instance).to.be();
    });

    it('should have the property virtualPaymentAddress (base name: "virtual_payment_address")', function() {
      // uncomment below and update the code to test the property virtualPaymentAddress
      //var instance = new BecknOdrApiSpecification.PaymentParams();
      //expect(instance).to.be();
    });

    it('should have the property sourceBankCode (base name: "source_bank_code")', function() {
      // uncomment below and update the code to test the property sourceBankCode
      //var instance = new BecknOdrApiSpecification.PaymentParams();
      //expect(instance).to.be();
    });

    it('should have the property sourceBankAccountNumber (base name: "source_bank_account_number")', function() {
      // uncomment below and update the code to test the property sourceBankAccountNumber
      //var instance = new BecknOdrApiSpecification.PaymentParams();
      //expect(instance).to.be();
    });

    it('should have the property sourceVirtualPaymentAddress (base name: "source_virtual_payment_address")', function() {
      // uncomment below and update the code to test the property sourceVirtualPaymentAddress
      //var instance = new BecknOdrApiSpecification.PaymentParams();
      //expect(instance).to.be();
    });

  });

}));
