/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BecknOdrApiSpecification);
  }
}(this, function(expect, BecknOdrApiSpecification) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BecknOdrApiSpecification.ReplacementTerm();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReplacementTerm', function() {
    it('should create an instance of ReplacementTerm', function() {
      // uncomment below and update the code to test ReplacementTerm
      //var instance = new BecknOdrApiSpecification.ReplacementTerm();
      //expect(instance).to.be.a(BecknOdrApiSpecification.ReplacementTerm);
    });

    it('should have the property fulfillmentState (base name: "fulfillment_state")', function() {
      // uncomment below and update the code to test the property fulfillmentState
      //var instance = new BecknOdrApiSpecification.ReplacementTerm();
      //expect(instance).to.be();
    });

    it('should have the property replaceWithin (base name: "replace_within")', function() {
      // uncomment below and update the code to test the property replaceWithin
      //var instance = new BecknOdrApiSpecification.ReplacementTerm();
      //expect(instance).to.be();
    });

    it('should have the property externalRef (base name: "external_ref")', function() {
      // uncomment below and update the code to test the property externalRef
      //var instance = new BecknOdrApiSpecification.ReplacementTerm();
      //expect(instance).to.be();
    });

  });

}));
