/**
 * Beckn ODR API Specification
 * Adaptation of Beckn protocol for the ODR sector.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BecknOdrApiSpecification);
  }
}(this, function(expect, BecknOdrApiSpecification) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BecknOdrApiSpecification.SelectPostRequestContext();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SelectPostRequestContext', function() {
    it('should create an instance of SelectPostRequestContext', function() {
      // uncomment below and update the code to test SelectPostRequestContext
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be.a(BecknOdrApiSpecification.SelectPostRequestContext);
    });

    it('should have the property domain (base name: "domain")', function() {
      // uncomment below and update the code to test the property domain
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property location (base name: "location")', function() {
      // uncomment below and update the code to test the property location
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property action (base name: "action")', function() {
      // uncomment below and update the code to test the property action
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property bapId (base name: "bap_id")', function() {
      // uncomment below and update the code to test the property bapId
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property bapUri (base name: "bap_uri")', function() {
      // uncomment below and update the code to test the property bapUri
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property bppId (base name: "bpp_id")', function() {
      // uncomment below and update the code to test the property bppId
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property bppUri (base name: "bpp_uri")', function() {
      // uncomment below and update the code to test the property bppUri
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property transactionId (base name: "transaction_id")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property messageId (base name: "message_id")', function() {
      // uncomment below and update the code to test the property messageId
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property key (base name: "key")', function() {
      // uncomment below and update the code to test the property key
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

    it('should have the property ttl (base name: "ttl")', function() {
      // uncomment below and update the code to test the property ttl
      //var instance = new BecknOdrApiSpecification.SelectPostRequestContext();
      //expect(instance).to.be();
    });

  });

}));
